<style>
.highcharts-container { min-width: 210px; height: 400px; width: 100px; margin: 0 auto; max-width:100% !important;}
label{
	text-align:right; font-size:15px !important;
}
thead tr{
	background-color:#b7b7b7;color:white;
}
.datepicker table tr td, .datepicker table tr th {
    border-radius: 0px !important;
}
@media (min-width: 992px){
	.card form .col-sm-2{
		padding: 0px 6px !important;
	}
}
.chosen-container {
    margin: 5px 0 0 0;
}
.form-group {
    margin: 0px 0 0 0 !important;
}
th{
    text-align:center !important;
	border : 1px solid lightgray;
}
td{
	text-align:left !important;
}

td:nth-child(7),td:nth-child(8),td:nth-child(9){
	text-align:center !important;
}
</style>
<script src="<?php echo $this->basePath(); ?>/js/jquery.table2excel.min.js"></script>
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-lg-12 col-md-12 col-sm-12">
				<section class="content">
					<div class="">
						<div class="col-md-12">
							<div class="card">
								<div class="card-header" style="background-color:#f44336 !important;">
									<h4 class="title">Booking Report</h4>
									<p class="category">Booking report</p>
								</div>
								  <div class=" card-content">
									<div class="well">
									<div class="box box-danger">
										<form action="<?php echo $this->basePath(); ?>/dashboard/booking-report" type="GET">
										<div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label for="tanggal1" class="col-sm-2 control-label">Tanggal</label>
                                                    <div class="col-sm-3">
                                                      <input type="text" name="start_date" id="start_date" class="form-control datepicker" value="<?php if(isset($_GET['start_date'])){echo $_GET['start_date'];}else{echo date('d-m-Y');};?>" style="padding: 0px 20px;">
                                                    </div>
                                                    <div class="col-sm-3">
                                                      <input type="text" name="end_date" id="end_date" class="form-control datepicker" value="<?php if(isset($_GET['end_date'])){echo $_GET['end_date'];}else{echo date('d-m-Y');};?>" style="padding: 0px 20px;">
                                                    </div>
                                                </div>
                                            </div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label for="unit" class="col-sm-2 control-label">Regional </label>
													<div class="col-sm-8">
														<select name="c_reg" id="c_reg" class="form-control chosen-select1">
															<option value="0"> - Semua Regional -</option>
														</select>
													</div>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label for="unit" class="col-sm-2 control-label">Cabang</label>
													<div class="col-sm-8">
														<select name="c_cabang" id="c_cabang" class="form-control chosen-select2">
															<option value="0"> - Semua Cabang - </option>
														</select>
													</div>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label for="unit" class="col-sm-2 control-label">Unit</label>
													<div class="col-sm-8">
														<select name="c_unit" id="c_unit" class="form-control chosen-select3">
															<option value="0"> - Semua Unit - </option>
														</select>
													</div>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-12">
												<div class="form-group">
													<label for="unit" class="col-sm-2 control-label">Pelanggan</label>
													<div class="col-sm-8">
														<select name="prioritas" id="prioritas" class="form-control chosen-select3">
																<?php foreach($this->hvc as $row){
																		?>
																			<option value="<?php echo $row['prefix']?>"><?php echo $row['desc']?></option>
																		<?php
																	}?>				
														</select>
													</div>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-sm-12">
											  <button type="submit" id="sendzz" class="btn btn-danger" style="float:right;">Pilih</button>
											</div>
										</div>
										</form>
									</div>
								  </div>
								  </div>
								  <div class="row">
									<div class="col-xs-12">
									  <div class="box card-content">
                                          <div class="box-body table-responsive">
                                            <button id='btnExport_example2' class='btn btn-danger' onclick='return klik_download()'>Excel</button>
                                            <table id="example2" aria-describedby="table example2" class="table table-striped table-hover" width="100%">
                                                <thead>
                                                <tr>
                                                  <th scope="col" rowspan="2">Id Booking</th>
												  <th scope="col" rowspan="2">Nama Unit</th>
                                                  <th scope="col" colspan="2">Waktu</th>
                                                  <th scope="col" rowspan="2">nama Pelanggan</th>
                                                  <th scope="col" rowspan="2">No. HP</th>
                                                  <th scope="col" rowspan="2">No. Layanan</th>
                                                  
                                                  <th scope="col" rowspan="2">Prioritas</th>
                                                  <th scope="col" rowspan="2">Nomor Antrian</th>
												  <th scope="col" rowspan="2">Regional</th>
												  <th scope="col" rowspan="2">Cabang</th>
												  <th scope="col" rowspan="2">Status</th>
                                                </tr>
                                                <tr>
                                                  <th scope="col">Tanggal Daftar</th>
                                                  <th scope="col">Tanggal Kunjungan</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                    
                                                </tbody>
                                              </table>
                                            </div>
                                        </div>
                                    </div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</div>
		  </div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function($){
		$('.chosen-select1').chosen({no_results_text: "Oops, nothing found!",width:"95%" });
		$('.chosen-select2').chosen({no_results_text: "Oops, nothing found!",width:"95%" });
		$('.chosen-select3').chosen({no_results_text: "Oops, nothing found!",width:"95%" });
	});
	
	$('.datepicker').datepicker({
		format: "dd-mm-yyyy",
		autoclose: true,
		startView: 3,
		maxViewMode: 3,
		todayBtn: "linked",
		clearBtn: true,
		language: "id"
	});
	
	<?php if(isset($_GET['start_date'])){?>
		var start_dtm = '<?php echo date("Ymd",strtotime($_GET['start_date']));?>';
		var end_dtm = '<?php echo date("Ymd",strtotime($_GET['end_date']));?>';
	<?php }else{?>
		var start_dtm = '<?php echo date("Ymd");?>';
		var end_dtm = '<?php echo date("Ymd");?>';
	<?php }?>
	
	$(document).ready(function(){
		$('.chosen-select1').chosen({no_results_text: "Data tidak ada!",width:"95%"});
		$('.chosen-select2').chosen({no_results_text: "Data tidak ada!",width:"95%"});
		$('.chosen-select3').chosen({no_results_text: "Data tidak ada!",width:"95%"});
	});
	
	$( "#c_reg" ).change(function() {
		var reg = $("#c_reg").val();
		$('#c_cabang').empty();
		<?php if(!isset($this->data['cabang']) || empty($this->data['cabang'])){?>
		$('#c_cabang').append('<option value="0"> Semua  </option>');
		<?php } ?>
		$.ajax({
			url: '<?php echo $this->basePath()?>/data/load-cabang', // ini API nya
			type: "POST",
			data: {"c_reg" : reg },
			success: function(datax) {
				var dataJson = datax.data;
				$.each(dataJson, function(i, item) {
					var $content = $('#c_cabang');
					<?php if(isset($this->data['cabang']) && !empty($this->data['cabang'])){
						?>
							if("<?php echo $this->data['cabang']?>" == item.c_cabang){
								$content.append('<option selected value="'+ item.c_cabang +'" rel="'+ item.l_cabang +'">'+ item.l_cabang +'</option>');
								$('#c_cabang').change();
							}
						<?php
					}else{
						?> 
							$content.append('<option value="'+ item.c_cabang +'" rel="'+ item.l_cabang +'">'+ item.l_cabang +'</option>');
						<?php
					}?>
					
				});
				
				<?php if(isset($_GET['c_cabang']) && $_GET['c_cabang'] != '0' && (!isset($this->data['cabang']) || empty($this->data['cabang']))){?>
					$('#c_cabang').val('<?php echo $_GET['c_cabang'];?>').change();
				<?php } ?>
				$('.chosen-select2').trigger("chosen:updated");
			}
		});
	});
	
	$( "#c_cabang" ).change(function() {
		var cabang = $("#c_cabang").val();
		$('#c_unit').empty();
		<?php if(!isset($this->data['c_unit']) || empty($this->data['c_unit'])){?>
		$('#c_unit').append('<option value="0"> Semua </option>');
		<?php } ?>
		$.ajax({
			url: '<?php echo $this->basePath()?>/data/load-unit', // Ini API, untuk basepath silahkan disesuaikan dengan url masing-masing
			type: "POST",
			data: {"c_cabang" : cabang },
			success: function(datax) {
				var dataJson = datax.data;
				$.each(dataJson, function(i, item) {
					var $content = $('#c_unit');
					<?php if(isset($this->data['c_unit']) && !empty($this->data['c_unit'])){
						?>
							if("<?php echo $this->data['c_unit']?>" == item.c_unit){
								$content.append('<option selected value="'+ item.c_unit +'" rel="'+ item.l_unit +'">'+ item.l_unit +'</option>');
							}
						<?php
					}else{
						?> 
							$content.append('<option value="'+ item.c_unit +'" rel="'+ item.l_unit +'">'+ item.l_unit +'</option>');
						<?php
					}?>
					
				});
				
				<?php if(isset($_GET['c_unit']) && $_GET['c_unit'] != '0' && (!isset($this->data['c_unit']) || empty($this->data['c_unit']))){?>
					$('#c_unit').val('<?php echo $_GET['c_unit'];?>').change();
				<?php } ?>
				$('.chosen-select3').trigger("chosen:updated");
			}
		});
	});
	
	$.ajax({
		url: '<?php echo $this->basePath()?>/data/load-reg',
		type: "POST",
		data: {},
		success: function(datax) {
			var dataJson = datax.data;
			<?php if(!isset($this->data['regional']) || empty($this->data['regional'])){?>
			$('#c_reg').append('<option value="0"> Semua </option>');
			<?php } ?>
			$.each(dataJson, function(i, item) {
				var $content = $('#c_reg');
				<?php if(isset($this->data['regional']) && !empty($this->data['regional'])){
					?>
						if("<?php echo $this->data['regional']?>" == item.c_reg){
							$content.append('<option selected value="'+ item.c_reg +'" rel="'+ item.l_reg +'">'+ item.l_reg +'</option>');
							$('#c_reg').change();
						}
					<?php
				}else{
					?> 
						$content.append('<option value="'+ item.c_reg +'" rel="'+ item.l_reg +'">'+ item.l_reg +'</option>');
					<?php
				}?>
				
			});
			
			<?php if(isset($_GET['c_reg']) && $_GET['c_reg'] != '0' && (!isset($this->data['regional']) || empty($this->data['regional']))){?>
				$('#c_reg').val('<?php echo $_GET['c_reg'];?>').change();
			<?php } ?>
			$('.chosen-select1').trigger("chosen:updated");
		}
	});
	
	
	<?php if(isset($_GET['prioritas']) && $_GET['prioritas'] != '0'){?>
		$('#prioritas').val("<?php echo $_GET['prioritas'];?>");
		$('.chosen-select3').trigger("chosen:updated");
	<?php } ?>
	
	
	$('#example2').dataTable( {
		"serverSide": true,
		"processing": true,
        "language": {
            processing: '<span class="pull-center">Loading...</span> '},
		"ajax": {
			"url": '<?php echo $this->basePath()?>/data/data-booking-report',
			"type": 'POST',
			"data": {
				"from" : start_dtm, 
				"to" : end_dtm,
                
				<?php if(isset($_GET['prioritas']) && $_GET['prioritas'] != '0'){?> 
                    "prioritas": "<?php echo $_GET['prioritas'];?>", 
				<?php }else{?>
                    "prioritas" : $('#prioritas').val(),
				<?php } ?>
                
				<?php if(isset($_GET['c_unit']) && $_GET['c_unit'] != '0'){?> 
                    "c_unit": "<?php echo $_GET['c_unit'];?>", 
				<?php }else if(isset($this->data['c_unit']) || !empty($this->data['c_unit'])){?>
                    "c_unit": "<?php echo $this->data['c_unit'];?>", 
				<?php }else{ ?>
                    "c_unit": $('#c_unit').val(),
				<?php } ?>
                
				<?php if(isset($_GET['c_reg']) && $_GET['c_reg'] != '0'){?> 
                    "c_reg": "<?php echo $_GET['c_reg'];?>", 
				<?php }else if(isset($this->data['regional']) || !empty($this->data['regional'])){?>
                    "c_reg": "<?php echo $this->data['regional'];?>", 
				<?php }else{ ?>
                    "c_reg": $('#c_reg').val(),
				<?php } ?>
                
				<?php if(isset($_GET['c_cabang']) && $_GET['c_cabang'] != '0'){?> 
                    "c_cabang": "<?php echo $_GET['c_cabang'];?>", 
				<?php }else if(isset($this->data['cabang']) || !empty($this->data['cabang'])){?>
                    "c_cabang": "<?php echo $this->data['cabang'];?>", 
				<?php }else{ ?>
                    "c_cabang": $('#c_cabang').val(), 
				<?php } ?>
			}
		},
		"columns": [
			{ "data": "BOOKING_ID", "name": "booking_id" },
			{ "data": "UNIT_NAME", "name": "unit_name" },
			{ "data": "TANGGAL_BUAT", "name": "tanggal_buat" },
			{ "data": "TANGGAL_SELESAI", "name": "tanggal_selesai" },
			{ "data": "NAME", "name": "name" },
			{ "data": "NO_HP", "name": "no_hp" },
			{ "data": "NO_LAYANAN", "name": "no_layanan" },
			
			{ "data": "PRIORITAS", "name": "prioritas" },
			{ "data": "ANNOUNCE_CALL", "name": "announce_call" },
			{ "data": "L_UCS", "name": "l_ucs" },
			{ "data": "L_AREA", "name": "l_area" },
			{ "data": "STATUS", "name": "status" },
		],
	} );
    
	function klik_download(x){
		<?php if(isset($_GET['c_unit']) && $_GET['c_unit'] != '0'){?>
			var c_unit =  "<?php echo $_GET['c_unit'];?>";
		<?php }else if(isset($this->data['c_unit']) || !empty($this->data['c_unit'])){ ?>
			var c_unit =  "<?php echo $this->data['c_unit'];?>";
		<?php }else{
			?>
			var c_unit =  $('#c_unit').val();
			<?php
		} ?>
		
		<?php if(isset($_GET['c_reg']) && $_GET['c_reg'] != '0'){?>
			var c_reg=  "<?php echo $_GET['c_reg'];?>";
		<?php }else if(isset($this->data['regional']) || !empty($this->data['regional'])){ ?>
			var c_reg =  "<?php echo $this->data['regional'];?>";
		<?php }else{
			?>
			var c_reg =  $('#c_reg').val();
			<?php
		} ?>
		
		<?php if(isset($_GET['c_cabang']) && $_GET['c_cabang'] != '0'){?>
			var c_cabang =  "<?php echo $_GET['c_cabang'];?>";
		<?php }else if(isset($this->data['cabang']) || !empty($this->data['cabang'])){ ?>
			var c_cabang =  "<?php echo $this->data['cabang'];?>";
		<?php }else{
			?>
			var c_cabang =  $('#c_cabang').val();
			<?php
		} ?>
		
		<?php if(isset($_GET['prioritas']) && $_GET['prioritas'] != '0'){?>
			var prioritas=  "<?php echo $_GET['prioritas'];?>";
		<?php }else{
			?>
			var prioritas = $('#prioritas').val();
			<?php
		} ?>
		
		var prioritas = $('#prioritas').val();
		
		window.open('<?php echo $this->basePath(); ?>/dashboard/rekapexcelbooking?from='+start_dtm+'&to='+end_dtm+'&c_reg='+c_reg+'&c_cabang='+c_cabang+'&c_unit='+c_unit+'&prioritas='+prioritas+'','_blank');
	}
</script>
