
<style>
.cinema-seats {
  display: grid;
  grid-template-columns: repeat(9, auto); /* Set the number of columns to 9 */
  gap: 2px; /* Adjust the gap as needed */
  justify-content: center;
  padding: 10px;
}

.seat {
  width: 50px;
  height: 50px;
  margin: 5px;
  background-color: #ccc;
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 14px;
}
.seat.selected {
  background-color: #28a745; /* Ganti dengan warna yang diinginkan */
  color: #fff; /* Ganti dengan warna teks yang sesuai */
}
.kursi {
  width: 50px;
  height: 50px;
  margin: 5px;
  background-color: #ccc;
  display: flex;
  justify-content: center;
  align-items: center;
  font-size: 14px;
}
.staircase {
  background-color: #FFF;
}
</style>
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- DataTables CSS -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">

<!-- DataTables JS -->
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>

<!-- sweetalart -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script type="text/javascript">
    function orderTiket(){
    id = $('#id_film').text()
    nomer_duduk = $('.selected').text();
    var chunks = nomer_duduk.match(/(\d+[A-Za-z]|[A-Za-z]+)/g);

    // Convert the chunks to lowercase and create the desired string
    var splitNumerDuduk = chunks.map(function(chunk) {
      return chunk.toUpperCase();
    }).join(',');
    $('#nomer_kursi').text(splitNumerDuduk) 

    // input to database
    var input= {       
       id_film: id,
       id_status_pembayaran: 1,
       nomor_duduk : splitNumerDuduk
      }
      Swal.fire({
        title: "Are you sure?",
        text: "You won't be able to revert this!",
        // icon: "warning",
        html: `
              You can use <b>bold text</b>,
              and other HTML tags
            `,
        showCancelButton: true,
        confirmButtonColor: "#3085d6",
        cancelButtonColor: "#d33",
        confirmButtonText: "Yes, delete it!"
      }).then((result) => {
        if (result.isConfirmed) {
          $.ajax({
            url: '<?php echo $this->basePath()?>/bioskop/order', // URL to your Zend controller action
            type: 'POST',                  // HTTP method (GET, POST, etc.)
            data: input,                // Data to be sent with the POST request
            dataType: 'json',              // Expected data type of the response
            success: function (data) {
                // Handle successful response
                console.log(data);
                Swal.fire({
                  title: "Pindah Kehalam Payment!",
                  text: "Your file has been deleted.",
                  icon: "success"
                });
                window.location = "<?php echo $this->basePath()?>/bioskop/payment";
            },
            error: function (xhr, status, error) {
                // Handle error response
                console.error(xhr.responseText);
                alert('An error occurred while processing the request.');
            }
          });
        }
      });
  }

$(document).ready(function(){
  
  var v_request = $.ajax({
    url: "<?php echo $this->basePath()?>/bioskop/listFilm",
    type: "GET",
    dataType: "json",
  });
  
  v_request.done(
    function(res, status, jqXHRz) {
      var data = res.data;
      for (var i = 0; i < data.length; i++) {
        var html = `<tr class="select" data-id='${data[i].id_film}' data-harga='${data[i].harga_tiket}' data-nama_film='${data[i].nama_film}' data-image="${data[i].film_image}" data-jam="${data[i].jam_tayang}" onclick="select_film(this)">
            <th scope="row" id="img"><img src="<?php echo $this->basePath('img/'); ?>${data[i].film_image}"  alt='${data[i].nama_film}' width="200" height="300"/></th>
            <td             id="nama" >
              <div class="col-xs-9 content-media">
                <a href="#" title="Fear of a Black Planet (2021) Film Subtitle Indonesia Streaming / Download" rel="bookmark">
                  <h3 style="text-transform: capitalize;">${data[i].nama_film}</h3>
                </a>
                <p class="imdb"><i class="fa-star"></i> IMDb 7.3</p>
                <p class="category-media"><a href="/genre/action/" rel="category" title="Daftar film terbaru dan terlengkap Genre Action">Action</a>, <a href="/genre/drama/" rel="category" title="Daftar film terbaru dan terlengkap Genre Drama">Drama</a>, <a href="/genre/thriller/" rel="category" title="Daftar film terbaru dan terlengkap Genre Thriller">Thriller</a>, <a href="/country/united-states/" rel="category" title="Daftar film terbaru dan terlengkap negara United States">United States</a>, <a href="/quality/webrip/" rel="category" title="Daftar film terbaru dan terlengkap kualitas film WEBRip">WEBRip</a>, <a href="/year/2021/" rel="category" title="Daftar film terbaru dan terlengkap tahun 2021">2021</a>, <a href="/size/1080/" rel="category" title="Daftar film terbaru dan terlengkap resolusi 1080">1080</a></p>
                <a href="#" class="btn btn-default btn-xs fancybox" title="Nonton Cuplikan Film Fear of a Black Planet (2021)" target="_blank" rel="nofollow">TRAILER</a>
              </div>
            </td>
            <td id="jam" >${data[i].jam_tayang}</td>
        </tr>`;
        $('#tbody').append(html);
      }
    $('#list-film').DataTable()
    }
  );
});




</script>

<div class="card" id="server" style="display:contents">
  <div class="card-body">
    <h5 class="card-title">  BIOSKOP XXI  </h5>
      <table class="table" id="list-film">
        <thead>
            <tr>
                <th scope="col" >Movie</th>
                <th scope="col" >Judul</th>
                <th scope="col" >Jam Tayang</th>
            </tr>
        </thead>
        <tbody id="tbody"></tbody>
      </table>
  </div>
</div>


<!-- card order -->
<div class="row">
  <div class="col-sm-6" id="nomor_kursi" hidden>
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Nomor Kursi</h3>
        <!-- kursi -->
        <div class="cinema-seats"></div>
      </div>
    </div>
  </div>
  <div class="col-sm-6" id="detail-film-order" hidden>
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Detail Film Order</h3>
          <p class="card-text">
            <table class="table">
              <thead>
                  <tr>
                      <th scope="col" colspan=3>Movie</th>
                  </tr>
              </thead>
              <tbody id="tbody-detail-film">
                
              </tbody>
            </table>
          </p>
          <button onclick="orderTiket()" class="btn btn-success" id="btnOrder" style="display:block">Order</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  const seatsContainer = document.querySelector('.cinema-seats');

  const jumlahBaris = 8; //add baris
  const jumlahKolom = 8; 
    for (let i = 1; i <= jumlahBaris; i++) {
      for (let j = 1; j <= jumlahKolom; j++) {
          const kursi = document.createElement('div');
          kursi.classList.add('kursi');
          kursi.classList.add('btn');
          kursi.classList.add('seat');
          kursi.classList.add('kode'+i);
          kursi.textContent = `${i}${String.fromCharCode(64 + j)}`;
          seatsContainer.appendChild(kursi);

          if (j === 4) {
            const kursi = document.createElement('div');
            kursi.classList.add('staircase');
            kursi.style.alignSelf = 'center';
            kursi.style.padding = '6px 12px';
            kursi.textContent = `${String.fromCharCode(64 + i)}`;
            seatsContainer.appendChild(kursi);
          }

        kursi.addEventListener('click', function () {
        // Mengubah warna kursi
        kursi.classList.toggle('selected');
        nomer_duduk = $('.selected').text();

        if (nomer_duduk ==""){
          $('#nomer_kursi').html('<button class="btn btn-danger">Pilih Kursi</button>');
          $('#btnOrder').hide()
        }else{
            $('#btnOrder').show()
              var chunks = nomer_duduk.match(/(\d+[A-Za-z]|[A-Za-z]+)/g);
        
              // Convert the chunks to lowercase and create the desired string
              var splitNumerDuduk = chunks.map(function(chunk) {
                return chunk.toUpperCase();
              }).join(',');

              

              $('#nomer_kursi').text(splitNumerDuduk)
          
        }
        });
      }
  }

function select_film(row) {
  var nama = row.getAttribute("data-nama_film");
  var img = row.getAttribute("data-image");
  var jam = row.getAttribute("data-jam");
  var harga = row.getAttribute("data-harga");
  var id = row.getAttribute("data-id");

  $('#detail-film-order').prop('hidden', false)
  $('#nomor_kursi').prop('hidden', false)
  $('#btnOrder').hide()
  
  $('.kursi').removeClass('selected');
  $('#tbody-detail-film').html(
    `<tr>
                <td rowspan=4><img src="<?php echo $this->basePath('img/'); ?>`+img+`" alt="movie" width="100" height="150"/></td>
                <td>Judul</td>
                <td>`+nama+`</td>
                <td style="display:none" id="id_film">`+id+`</td>
              </tr>
              <tr>
                <td>Jam Tayang</td>
                <td>`+jam+`</td>
              </tr>
              <tr>
                <td>Harga Tiket</td>
                <td>`+harga+`</td>
              </tr>
              <tr>
                <td>Nomor Kursi</td>
                <td id="nomer_kursi"><small style="padding: 5px;background-color:#c55050;color:#fff">Belum ditambahkan.</small></td>
              </tr>`
  )
}

</script>
