<script type="text/javascript">
$(document).ready(function(){
  var v_request = $.ajax({
    url: "<?php echo $this->basePath()?>/application/index/var-server",
    type: "GET",
    dataType: "json",
  });
  
  v_request.done(
    function(data, status, jqXHRz) {
      console.log(data)
      $('#server').append(`<p>`+data+`</p>`)
        // for (var key in data) {
        //     if (data.hasOwnProperty(key)) {
        //         $('#server').append('<p>' + key + ' ==> ' + data[key] + '</p>');
        //         $('#server').append('<p>' + status + '</p>');
        //     }
        // }
    }
  );
});
</script>

<div id="server" class="row">
</div>
